CC = gcc
CFLAGS = -Wall -Wextra -O2
TARGET = app
SRC = main.c

all:
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET)

run:
	./$(TARGET)

clean:
	rm -f $(TARGET)

help:
	@echo "Usage:"
	@echo " make        -> build the application"
	@echo " make run    -> run the application"
	@echo " make clean  -> remove binary"
